export const Styles = (language) => ({
  bannerContainer: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    height: { xs: "100%", sm: "70vh" },
    mt: 7,
    pb: { xs: 5, sm: 0 },
  },

  image: {
    width: { xs: "400%", md: "50%" },
    height: { xs: "400%", md: "100%" },
    objectFit: "cover",
    position: "absolute",
    right: language === "ar" ? 0 : "",
    left: language === "en" ? 0 : "",
    transform: language === "en" ? "rotate(180deg)" : "",
  },
  boxHero: {
    position: "relative",
    zIndex: 100,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    height: "100%",
    mr: language === "ar" ? { xs: 0, md: 5 } : 0,
    px: 5,
    py: { xs: 4, sm: 0 },
  },
  title: {
    fontSize: { xs: "25pz", sm: "50px" },
    fontWeight: "bold",
    lineHeight: { xs: "45px", sm: "75px" },
    color: "#fff",
  },
  description: {
    marginTop: "16px",
    fontSize: "18px",
    lineHeight: "28px",
    color: "#fff",
    maxWidth: "50ch",
    letterSpacing: "1px",
  },
  button: {
    backgroundColor: "white !important",
    color: "purple !important",
    marginTop: "16px",
    fontWeight: "bold",
    borderRadius: "10px",
    fontSize: "18px",
    fontWeight: 700,
    gap: 1,
    width: "250px",
  },
  imageHero: {
    position: "absolute",
    top: 0,
    left: language === "en" ? "" : 0,
    right: language === "en" ? 0 : "",
    width: "70%",
    height: "100%",
    objectFit: "cover",
    zIndex: "-5",
  },
});
