export const Styles = {
  root: {
    width: 340,
    height: "100%",
    backgroundColor: "#fff",
    borderRadius: 5,
    padding: 2,
    position: "relative",
    overflowY: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
    pb: 2,
    borderBottom: "2px solid #D9D9D9",
    height: "50px",
  },
  cartEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "calc(100% - 140px)",
    gap: 2,
  },
  imgCart: {
    width: 60,
    height: 60,
  },
  textCart: {
    color: "#9F9F9F",
    fontSize: "24px",
    fontWeight: 500,
  },
  containerItem: {
    height: "calc(100% - 150px)",
    // height: "200px",
    overflow: "auto",
  },
  itemRow: {
    display: "flex",
    alignItems: "flex-start",
    marginBottom: 2,
    gap: 2,
    pb: 2,
  },
  span: {
    color: "#792A86",
    mr: 0.5,
  },
  toggleButton: {
    width: 15,
    height: 15,
    borderRadius: "50%",
    minWidth: "auto",
    padding: 0,
    mx: 1,
    border: "2px solid transparent",
    transition: "border 0.2s ease-in-out",
    border: "3px solid #eee",
    "&:hover": {
      border: "2px solid gray",
    },
    "&.Mui-selected": {
      border: "2px solid black",
    },
  },
  itemImage: {
    width: 100,
    height: 100,
    borderRadius: 3,
    objectFit: "cover",
    marginRight: 2,
  },
  itemInfo: {
    flexGrow: 1,
  },
  sizeColor: {
    display: "flex",
    gap: 2,
    my: 1,
  },
  divider: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
    paddingTop: 2,
    borderTop: `1px solid #ccc`,
    position: "absolute",
    left: 0,
    bottom: 0,
    width: "100%",
    height: "100px",
    zIndex: 5,
    px: 1,
    py: 2,
    backgroundColor: "#fff",
  },
  totalRow: {
    display: "flex",
    gap: 1,
  },
  checkoutButton: {
    backgroundColor: "transparent",
    borderRadius: "8px",
    border: "1px solid #000",
    px: 2,
    py: 0.5,
    transition: "all .2s",
    ".btn": {
      backgroundColor: "transparent",
      color: "#000",
      "&:hover": {
        color: "#fff",
      },
    },
    "&:hover": {
      backgroundColor: "#6a1b9a",
    },
  },
};
